package restaurant.menu.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Data;



@Entity
@Data
@Schema(description = "Entity Product to register all products")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_product")
    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product Id", example = "1")
    private int idProduct;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product numberItem (autogenerated)", example = "9c0bd87c-f3fb-4d34-9754-3aa8d2b188c0")
    @Column(name = "number_item")
    private String numberItem;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product type (ENUM)", example = "PIZZA OR PANINO OR PIATTO_DI_TERRA ..")
    @Enumerated(EnumType.STRING)
    private Type type;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product nameProduct", example = "Panino al salame / sandwich pepperoni")
    @Column(name = "name_product")
    private String nameProduct;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product price", example = "20.20")
    private double price;


    @Schema(accessMode = Schema.AccessMode.READ_ONLY, description = "Product imageProduct", example = "http://wwww.paninoImmagini.it")
    @Column(name = "image_product")
    private String imageProduct;

    @ManyToOne
    @JoinColumn(name = "id_user")
    private User user;
}
